client_config_backend: file
client_config:
    client_id: 948978544941-a08hv6d7egvltrmjrnq54taf05bmil5r.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive